### ISSUE TITLE
Swift Package Manager support

### ISSUE THREAD

**Issue by toemat** [boxcast/boxcast-sdk-apple#12]
Hi! We're evaluating BoxCast and I'm wondering if you would integrate Swift Package Manager as an integration option?

I can take a shot at the Package.swift manifest and open a PR if that's helpful?

Thank you!

**Comment by bikegriffith** [comment]
Hi @toemat! Sorry for the delayed response.  I'd love if you could open a PR; we're certainly open to switching to Swift Package Manager!

**Comment by rwhite35** [comment]
Hey @toemat thanks for the PR and update.  Your addition was merged into master with only one small change. Reset channelId back to the default string for consistency sake. Otherwise, your addition works as expected. Thanks for contributing!
